/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mdpf.guiswingorderlinuxmdpf;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Matteo Di Paolo Formiconi
 * @version 1.0
 */
public class GuiSwingOrderLinuxMDPF extends javax.swing.JFrame {

    public GuiSwingOrderLinuxMDPF() {

        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        dlgLogoMDPF logoframe = new dlgLogoMDPF(this, true);

        logoframe.setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon("/home/matdipfor/NetBeansProjects/GuiSwingOrderLinuxMDPF/src/main/resources/imgMDPF/logoMDPF.png");
        setIconImage(icon.getImage());
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        reloj.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
this.getContentPane().setBackground(new java.awt.Color(245, 222, 179));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvieworder = new javax.swing.JButton();
        btncalculator = new javax.swing.JButton();
        btnabout = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btntakeorder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btninformation = new javax.swing.JButton();
        reloj = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TakeOrderApp v.1 by Matteo Di Paolo Formiconi");
        setMaximumSize(new java.awt.Dimension(561, 661));
        setMinimumSize(new java.awt.Dimension(561, 661));
        setPreferredSize(new java.awt.Dimension(561, 661));
        setResizable(false);

        btnvieworder.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        btnvieworder.setFocusPainted(false); // Elimina el borde de enfoque al hacer clic
        btnvieworder.setBackground(new java.awt.Color(255, 165, 0)); // Fondo naranja
        btnvieworder.setForeground(new java.awt.Color(0, 0, 0)); // Texto en negro
        btnvieworder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cambia el cursor a mano cuando pasas sobre el botón
        btnvieworder.setText("View full order");
        btnvieworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvieworderActionPerformed(evt);
            }
        });

        btncalculator.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        btncalculator.setFocusPainted(false); // Elimina el borde de enfoque al hacer clic
        btncalculator.setBackground(new java.awt.Color(255, 165, 0)); // Fondo naranja
        btncalculator.setForeground(new java.awt.Color(0, 0, 0)); // Texto en negro
        btncalculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cambia el cursor a mano cuando pasas sobre el botón
        btncalculator.setText("Calculator");
        btncalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculatorActionPerformed(evt);
            }
        });

        btnabout.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        btnabout.setFocusPainted(false); // Elimina el borde de enfoque al hacer clic
        btnabout.setBackground(new java.awt.Color(255, 165, 0)); // Fondo naranja
        btnabout.setForeground(new java.awt.Color(0, 0, 0)); // Texto en negro
        btnabout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cambia el cursor a mano cuando pasas sobre el botón
        btnabout.setText("About");
        btnabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        btnexit.setFocusPainted(false); // Elimina el borde de enfoque al hacer clic
        btnexit.setBackground(new java.awt.Color(255, 165, 0)); // Fondo naranja
        btnexit.setForeground(new java.awt.Color(0, 0, 0)); // Texto en negro
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cambia el cursor a mano cuando pasas sobre el botón
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btntakeorder.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        btntakeorder.setFocusPainted(false);
        btntakeorder.setBackground(new java.awt.Color(255, 165, 0));
        btntakeorder.setForeground(new java.awt.Color(0, 0, 0));
        btntakeorder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntakeorder.setText("Take full order");
        btntakeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntakeorderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(139, 69, 19));
        jLabel1.setText("GUI Swing Order MDPF");
        jLabel1.setToolTipText("");

        btninformation.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        btninformation.setFocusPainted(false); // Elimina el borde de enfoque al hacer clic
        btninformation.setBackground(new java.awt.Color(255, 165, 0)); // Fondo naranja
        btninformation.setForeground(new java.awt.Color(0, 0, 0)); // Texto en negro
        btninformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cambia el cursor a mano cuando pasas sobre el botón
        btninformation.setText("Information");
        btninformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformationActionPerformed(evt);
            }
        });

        reloj.setBackground(new java.awt.Color(245, 222, 179));

        jMenu1.setText("App");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("View full order");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Calculator");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Company");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Information");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntakeorder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btninformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnabout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvieworder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reloj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntakeorder)
                    .addComponent(btnvieworder))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninformation)
                    .addComponent(btnabout))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexit)
                    .addComponent(btncalculator))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculatorActionPerformed
        // TODO add your handling code here:
        String os = System.getProperty("os.name").toLowerCase();

        try {
            setLocationRelativeTo(null);
            if (os.contains("win")) {
                new ProcessBuilder("calc").start();
            } else if (os.contains("linux")) {
                new ProcessBuilder("kcalc").start();
            } else {
                JOptionPane.showMessageDialog(this, "Calculator is not supported on your operating system.", "Unsupported OS", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the calculator.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btncalculatorActionPerformed

    private void btntakeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntakeorderActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        TakeOrder ordertake = new TakeOrder();
        ordertake.setLocationRelativeTo(null);
        ordertake.setVisible(true);

        ordertake.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setEnabled(true);
            }
        });
    }//GEN-LAST:event_btntakeorderActionPerformed

    private void btninformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformationActionPerformed
        // TODO add your handling code here:
        JInformation ejemplo = new JInformation(this, true);
        ejemplo.setVisible(true);
    }//GEN-LAST:event_btninformationActionPerformed

    private void btnvieworderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvieworderActionPerformed
        // TODO add your handling code here:
        if (TakeOrder.orders.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no orders", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] customerNames = new String[TakeOrder.orders.size()];
        for (int i = 0; i < TakeOrder.orders.size(); i++) {
            customerNames[i] = TakeOrder.orders.get(i).getFullCustomerName();
        }

        String selectedCustomerName = (String) JOptionPane.showInputDialog(
                this,
                "Choose the order that you want to see:",
                "Choose order",
                JOptionPane.QUESTION_MESSAGE,
                null,
                customerNames,
                customerNames[0]
        );

        if (selectedCustomerName != null) {
            Order selectedOrder = null;
            for (Order order : TakeOrder.orders) {
                if (order.getFullCustomerName().equals(selectedCustomerName)) {
                    selectedOrder = order;
                    break;
                }
            }

            if (selectedOrder != null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Order details:\n" + selectedOrder.toString(),
                        "Selected order",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnvieworderActionPerformed

    private void btnaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutActionPerformed

        JOptionPane.showMessageDialog(this, "Developer: Matteo Di Paolo Formiconi\n Application: GUISwingOrderLinuxMDPF\n Version: 1.0", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnaboutActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Are you sure?");
        if (a == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Thank you for using GuiSwingOrderLinuxMDPF! Goodbye!");
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        btnvieworder.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        btncalculator.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        btnexit.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dlgLogoMDPF hola = new dlgLogoMDPF(this, rootPaneCheckingEnabled);
        hola.setVisible(rootPaneCheckingEnabled);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        btnabout.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        btninformation.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSwingOrderLinuxMDPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSwingOrderLinuxMDPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSwingOrderLinuxMDPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSwingOrderLinuxMDPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiSwingOrderLinuxMDPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btncalculator;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btninformation;
    private javax.swing.JButton btntakeorder;
    private javax.swing.JButton btnvieworder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private java.awt.Label reloj;
    // End of variables declaration//GEN-END:variables
}
