/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mdpf.guiswingorderlinuxmdpf;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author matdipfor
 */
public class TakeOrder extends javax.swing.JFrame {

    static ArrayList<Order> orders = new ArrayList<Order>();
    
    

    /**
     * Creates new form TakeOrder
     */
    public TakeOrder() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.getContentPane().setBackground(new java.awt.Color(245, 222, 179)); 
        invoiceno.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        takeawaybutton = new javax.swing.JRadioButton();
        restaurantbutton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tablenumbertextfield = new javax.swing.JTextField();
        tablenumberlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customercomments = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        creditcard = new javax.swing.JRadioButton();
        checkemail = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tippingbox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        invoiceyes = new javax.swing.JRadioButton();
        invoiceno = new javax.swing.JRadioButton();
        finishorderbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        timedatalabel = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();

        buttonGroup1.add(takeawaybutton);
        buttonGroup1.add(restaurantbutton);

        buttonGroup2.add(creditcard);
        buttonGroup2.add(cash);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(626, 701));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(139, 69, 19));
        jLabel1.setText("Take your order");

        takeawaybutton.setText("Takeaway");
        takeawaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeawaybuttonActionPerformed(evt);
            }
        });

        restaurantbutton.setText("Restaurant");
        restaurantbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantbuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel2.setText("Choose one:");

        tablenumbertextfield.setEnabled(false);

        tablenumberlabel.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        tablenumberlabel.setText("Table Number:");
        tablenumberlabel.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel3.setText("Full name:");

        jLabel4.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel5.setText("Comments:");

        customercomments.setColumns(20);
        customercomments.setRows(5);
        jScrollPane1.setViewportView(customercomments);

        jLabel6.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel6.setText("Grand Total:");

        jLabel7.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel7.setText("Payment Method:");

        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        creditcard.setText("Credit Card");
        creditcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardActionPerformed(evt);
            }
        });

        checkemail.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        checkemail.setText("Check email");
        checkemail.setFocusPainted(false);
        checkemail.setBackground(new java.awt.Color(255, 165, 0));
        checkemail.setForeground(new java.awt.Color(0, 0, 0));
        checkemail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkemailActionPerformed(evt);
            }
        });

        jLabel8.setText("Tip:");

        tippingbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "5%", "10%", "15%", "20%" }));

        jLabel9.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel9.setText("Invoice:");

        invoiceyes.setText("Yes");

        invoiceno.setText("No");

        finishorderbutton.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        finishorderbutton.setFocusPainted(false);
        finishorderbutton.setBackground(new java.awt.Color(255, 165, 0));
        finishorderbutton.setForeground(new java.awt.Color(0, 0, 0));
        finishorderbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finishorderbutton.setText("FINISH ORDER");
        finishorderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishorderbuttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel10.setText("Time&Data:");

        timedatalabel.setText(new Date().toString());

        refresh.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.setFocusPainted(false);
        refresh.setBackground(new java.awt.Color(255, 165, 0));
        refresh.setForeground(new java.awt.Color(0, 0, 0));
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(takeawaybutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(41, 41, 41)
                                                .addComponent(restaurantbutton))
                                            .addComponent(customername)
                                            .addComponent(email))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(tablenumberlabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tablenumbertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(checkemail))))
                                    .addComponent(jScrollPane1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(42, 42, 42)
                                        .addComponent(tippingbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(invoiceno))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(timedatalabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refresh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(invoiceyes)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cash)
                                                .addGap(60, 60, 60)
                                                .addComponent(creditcard)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(finishorderbutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(takeawaybutton)
                    .addComponent(restaurantbutton)
                    .addComponent(tablenumbertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablenumberlabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkemail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cash)
                    .addComponent(creditcard)
                    .addComponent(tippingbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(invoiceyes)
                    .addComponent(invoiceno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(timedatalabel)
                    .addComponent(refresh))
                .addGap(38, 38, 38)
                .addComponent(finishorderbutton)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restaurantbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantbuttonActionPerformed
        // TODO add your handling code here:
        tablenumberlabel.setEnabled(true);
        tablenumbertextfield.setEnabled(true);

    }//GEN-LAST:event_restaurantbuttonActionPerformed

    private void takeawaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeawaybuttonActionPerformed
        // TODO add your handling code here:
        tablenumberlabel.setEnabled(false);
        tablenumbertextfield.setEnabled(false);
    }//GEN-LAST:event_takeawaybuttonActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed

    private void creditcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        timedatalabel.setText(new Date().toString());
    }//GEN-LAST:event_refreshActionPerformed

    private void finishorderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishorderbuttonActionPerformed
        // TODO add your handling code here:
        boolean allValid = true;

   
    if (!takeawaybutton.isSelected() && !restaurantbutton.isSelected()) {
        JOptionPane.showMessageDialog(this, "Choose a place to eat", "Error", JOptionPane.ERROR_MESSAGE);
        allValid = false;
    }

    
    String tableNumber = "0";
    if (allValid && restaurantbutton.isSelected()) {
        String inputText = tablenumbertextfield.getText();
        if (inputText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table number is required", "Error", JOptionPane.ERROR_MESSAGE);
            allValid = false;
        } else {
            try {
                int number = Integer.parseInt(inputText);
                if (number < 1 || number > 50) {
                    JOptionPane.showMessageDialog(this, "Table number must be between 1 and 50", "Error", JOptionPane.ERROR_MESSAGE);
                    allValid = false;
                } else {
                    tableNumber = inputText;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid input for table number", "Error", JOptionPane.ERROR_MESSAGE);
                allValid = false;
            }
        }
    }

   
    String customerName = customername.getText();
    if (allValid) {
        if (customerName.isEmpty() /*|| !customerName.matches("[a-zA-Z]+")*/) {
            JOptionPane.showMessageDialog(this, "Customer name is required and must contain only letters", "Error", JOptionPane.ERROR_MESSAGE);
            allValid = false;
        }
    }

    
    String emailText = email.getText();
    if (allValid) {
        if (!emailText.isEmpty()&&!emailText.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$" )) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Error", JOptionPane.ERROR_MESSAGE);
            allValid = false;
        }
    }

   
    String grandTotalText = grandtotal.getText();
    if (allValid) {
        if (grandTotalText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Grand total is required", "Error", JOptionPane.ERROR_MESSAGE);
            allValid = false;
        } else {
            try {
                double grandTotalNumber = Double.parseDouble(grandTotalText);
                if (grandTotalNumber < 1) {
                    JOptionPane.showMessageDialog(this, "Grand total must be higher than 0", "Error", JOptionPane.ERROR_MESSAGE);
                    allValid = false;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid input for grand total", "Error", JOptionPane.ERROR_MESSAGE);
                allValid = false;
            }
        }
    }

   
    String paymentMethod = null;
    if (allValid) {
        if (cash.isSelected()) {
            paymentMethod = "Cash";
        } else if (creditcard.isSelected()) {
            paymentMethod = "Credit Card";
        } else {
            JOptionPane.showMessageDialog(this, "Choose a payment method", "Error", JOptionPane.ERROR_MESSAGE);
            allValid = false;
        }
    }

    
    String requestInvoice = null;
    if (allValid) {
        if (invoiceno.isSelected()) {
            requestInvoice = "No";
        } else if (invoiceyes.isSelected()) {
            requestInvoice = "Yes";
        } else {
            JOptionPane.showMessageDialog(this, "Choose an invoice option", "Error", JOptionPane.ERROR_MESSAGE);
            allValid = false;
        }
    }

   
    if (allValid) {
        String dateTime = timedatalabel.getText();
        String takeaway = takeawaybutton.isSelected() ? "Takeaway" : "Restaurant";
        String customerComments = customercomments.getText();
        String tipping = tippingbox.getSelectedItem().toString(); 

        
        Order newOrder = new Order(dateTime, takeaway, tableNumber, customerName, emailText, customerComments, grandTotalText, paymentMethod, tipping, requestInvoice);

        orders.add(newOrder);
        System.out.println(orders);
        JOptionPane.showMessageDialog(this, "Order created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        this.dispose();
    }

        
        


    }//GEN-LAST:event_finishorderbuttonActionPerformed

    private void checkemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkemailActionPerformed
        // TODO add your handling code here:
        if (!email.getText().isEmpty()&&!email.getText().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Error", JOptionPane.ERROR_MESSAGE);
            email.setText("");
        }
    }//GEN-LAST:event_checkemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cash;
    private javax.swing.JButton checkemail;
    private javax.swing.JRadioButton creditcard;
    private javax.swing.JTextArea customercomments;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField email;
    private javax.swing.JButton finishorderbutton;
    private javax.swing.JTextField grandtotal;
    private javax.swing.JRadioButton invoiceno;
    private javax.swing.JRadioButton invoiceyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JRadioButton restaurantbutton;
    private javax.swing.JLabel tablenumberlabel;
    private javax.swing.JTextField tablenumbertextfield;
    private javax.swing.JRadioButton takeawaybutton;
    private javax.swing.JLabel timedatalabel;
    private javax.swing.JComboBox<String> tippingbox;
    // End of variables declaration//GEN-END:variables
}
